// ui/src/views/Login.vue
<template>
  <div class="flex justify-center items-center h-full">
    <form
      class="xl:w-1/2 w-full flex items-center flex-col"
      @submit.prevent="login"
    >
      <div class="w-1/2">
        <div class="mb-4">
          <label class="block text-sm" for="teamname">
            teamname
          </label>
          <input type="text" v-model="teamname" id="teamname" required />
        </div>
        <div class="mb-4">
          <label class="block text-sm" for="password">
            password
          </label>
          <input type="password" v-model="password" id="password" required />
        </div>

        <input type="submit" value="Login" class="float-right" />
      </div>
      <div class="w-1/2">
        <p style="text-align: right;">
          forget your password?
          <router-link to="/reset-request">reset from here</router-link>
        </p>
      </div>
    </form>
  </div>
</template>

<script>
import Vue from "vue";
import API from "@/api";
import { errorHandle, message } from "@/message";
export default Vue.extend({
  data() {
    return {
      teamname: "",
      password: ""
    };
  },
  mounted() {
    if (this.$store.teamname != null) {
      this.$router.push("/");
    }
  },
  methods: {
    login() {
      API.post("/login", {
        teamname: this.teamname,
        password: this.password
      })
        .then(r => {
          message(this, r.data.message);
          this.$eventHub.$emit("login-check");
          this.$router.push("/");
        })
        .catch(e => {
          errorHandle(this, e);
        });
    }
  }
});
</script>

// ui/pages/login.tsx
import {
  Box,
  FormControl,
  FormLabel,
  Link,
  Text,
  VStack,
} from "@chakra-ui/react";
import { api } from "lib/api";
import useMessage from "lib/useMessage";
import NextLink from "next/link";
import { useRouter } from "next/router";
import { SubmitHandler, useForm } from "react-hook-form";
import Right from "../components/right";
import useAccount from "../lib/api/account";
import FormWrapper from "../components/formwrapper";
import FormItem from "../components/formitem";
import Input from "../components/input";
import Label from "../components/label";
import Button from "../components/button";

type LoginParams = {
  teamname: string;
  password: string;
};

const Login = () => {
  const {
    register,
    handleSubmit,
    formState: { errors },
  } = useForm<LoginParams>();
  const router = useRouter();
  const { mutate } = useAccount();
  const { message, error } = useMessage();
  const onSubmit: SubmitHandler<LoginParams> = async (values) => {
    try {
      const res = await api.post("/login", {
        teamname: values.teamname,
        password: values.password,
      });
      message(res);

      mutate();
      router.push("/");
    } catch (e) {
      error(e);
    }
  };
  return (
    <FormWrapper>
      <form onSubmit={handleSubmit(onSubmit)}>
        <FormItem>
          <Label htmlFor="teamname">teamname</Label>
          <Input id="teamname" {...register("teamname", { required: true })} />
        </FormItem>
        <FormItem>
          <Label htmlFor="password">password</Label>
          <Input
            id="password"
            type="password"
            {...register("password", { required: true })}
          />
        </FormItem>
        <FormItem>
          <Right>
            <Button type="submit">Login</Button>
          </Right>
        </FormItem>
        <p>
          <Link as={NextLink} href="/passwordreset_request">
            Forgot your password? You can reset your password here.
          </Link>
        </p>
      </form>
    </FormWrapper>
  );
};

export default Login;
