// ui/pages/register.tsx
import CountrySelector from "components/countryselector";
import { api } from "lib/api";
import useMessage from "lib/useMessage";
import { useRouter } from "next/router";
import { useState } from "react";
import { SubmitHandler, useForm } from "react-hook-form";
import Right from "../components/right";
import FormWrapper from "../components/formwrapper";
import FormItem from "../components/formitem";
import Input from "../components/input";
import Label from "../components/label";
import Button from "../components/button";

type RegisterParams = {
  email: string;
  teamname: string;
  password: string;
};

const Register = () => {
  const [country, setCountry] = useState("");
  const {
    register,
    handleSubmit,
    formState: { errors },
  } = useForm<RegisterParams>();
  const router = useRouter();
  const { message, error } = useMessage();
  const onSubmit: SubmitHandler<RegisterParams> = async (values) => {
    try {
      const res = await api.post("/register", {
        email: values.email,
        teamname: values.teamname,
        password: values.password,
        country: country,
      });
      message(res);

      router.push("/login");
    } catch (e) {
      error(e);
    }
  };
  return (
    <FormWrapper>
      <form onSubmit={handleSubmit(onSubmit)}>
        <FormItem>
          <Label htmlFor="email">email</Label>
          <Input
            id="email"
            type="email"
            autoComplete="email"
            {...register("email", { required: true })}
          />
        </FormItem>

        <FormItem>
          <Label htmlFor="teamname">teamname</Label>
          <Input
            id="teamname"
            autoComplete="username"
            {...register("teamname", { required: true })}
          />
        </FormItem>

        <FormItem>
          <Label htmlFor="password">password</Label>
          <Input
            id="password"
            type="password"
            autoComplete="new-password"
            {...register("password", { required: true })}
          />
        </FormItem>

        <FormItem>
          <Label htmlFor="country">country</Label>
          <CountrySelector
            id="country"
            value={country}
            onChange={(e) => setCountry(e.target.value)}
          />
        </FormItem>

        <FormItem>
          <Right>
            <Button type="submit">Register</Button>
          </Right>
        </FormItem>
      </form>
    </FormWrapper>
  );
};

export default Register;

// ui/src/views/Register.vue
<template>
  <div class="flex justify-center items-center h-full">
    <form class="xl:w-1/2 w-full flex items-center flex-col" @submit.prevent>
      <div class="w-1/2">
        <div class="mb-4">
          <label class="block text-sm" for="email">
            email
          </label>
          <input type="email" v-model="email" id="email" required />
        </div>

        <div class="mb-4">
          <label class="block text-sm" for="teamname">
            teamname
          </label>
          <input type="text" v-model="teamname" id="teamname" required />
        </div>

        <div class="mb-4">
          <label class="block text-sm" for="password">
            password
          </label>
          <input type="password" v-model="password" id="password" required />
        </div>

        <div class="mb-4">
          <label class="block text-sm" for="country">
            Country Code {{ country | countryFlag }}
          </label>
          <input type="text" v-model="country" id="country" />
        </div>

        <div class="mv-4">
          <input type="submit" value="Register" @click="register" />
        </div>
      </div>
    </form>
  </div>
</template>

<script>
import Vue from "vue";
import API from "@/api";
import { message, errorHandle } from "@/message";

export default Vue.extend({
  data() {
    return {
      email: "",
      password: "",
      teamname: "",
      country: ""
    };
  },
  mounted() {
    if (this.$store.teamname != null) {
      this.$router.push("/");
    }
  },
  methods: {
    register() {
      API.post("/register", {
        teamname: this.teamname,
        email: this.email,
        password: this.password,
        country: this.country
      })
        .then(r => {
          message(this, r.data.message);
          this.$router.push("/login");
        })
        .catch(e => {
          errorHandle(this, e);
        });
    }
  }
});
</script>
